### ISSUE TITLE
Load local fonts

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#105]
AFAIK, Pango can't do this currently - but I've seen some [blog entries](http://mces.blogspot.com/2015/05/how-to-use-custom-application-fonts.html) on making this less painful. Cross-platform compatibility is really hard since the OS is a big part of font loading/rendering/caching, so I'm not expecting this anytime soon.

**Comment by spilth** [comment]
I'm building my project on CircleCI and managed to get my "custom" fonts working on there with the following `circle.yml`:

```yaml
general:
  artifacts:
    - "_output"

dependencies:
  pre:
    - mkdir ~/.fonts
    - cp fonts/* ~/.fonts/

test:
  override:
    - bundle exec rake
```
