### ISSUE TITLE
Better n-up support and other POD support for save_sheet

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#126]
Initial description from BGG user azarkon:

> simple: add/modify save_sheet to have useful defaults: 9-up print and play(no bleed), 8-up print and play (full bleed), POD compliant formats (gamecrafter, PNP productions, and Drive-through cards, etc)

We can also make DSL methods for specific manufacturers too.

**Comment by andjd** [comment]
I'd like to make bleed/trim an instance variable of the Deck class with a default value of 0.  I feel that it's a detail that's conceptually immutable like deck size and dimensions, and this would allow me to write the save sheet method so it wouldn't need a trim argument. We could then change all the render methods to take a :bleed argument that would equal :full, :none, or :safe too.  

thoughts?

**Comment by andymeneely** [comment]
The default `trim` option to `save_sheet` is already 0. 

(Instance variable isn't the way to accomplish this anyway)

I don't like full/none/safe as being an options here. That would make the Squib code too dependent on users' needs and I don't want to assume. Can just as easily be defined in a layout file. Perhaps we can include built-in layout files for popular templates. When it comes to options to methods, I'd rather have a minimal set of options, and `trim`, `gap`, and `margin` seem to be enough.

What I do currently is something like this:

```yml
# layout.yml
cut_line:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050
  radius: 0
  stroke_width: 3.0
  stroke_color: black
  trim: 37.5
outline:
  extends: cut_line
  radius: 25
  stroke_width: 6.0
```

Then my code still has the word "cut_line" to make it more readable:
```ruby
rect layout: 'cut_line'
```

Now currently, `save_sheet` doesn't take `trim` from a layout file for some silly reason. I think that's what we really want. That would mean we could do:

```ruby
save_sheet layout: 'cut_line'
```
