### ISSUE TITLE
Nil error on empty layout field

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#14]
The `extends` functionality doesn't account for a possible nil in a layout yaml file like this:

``` yaml
title:
    #nothing here - yaml defaults to nil
subtitle:
    font: 'Sans'
```
