### ISSUE TITLE
Allow for units and percentages in strings

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#18]
Allow for some arguments like x,y, width, and height to allow for unit conversion and percentage of width and height. For example, 

``` yml
title:
  width: 50% #computes to 50% of the width of the card
  height: 50% #computes to 50% of the width of the card
  x: 1in # goes to 300 pixels if @dpi is set to 300.
```
