### ISSUE TITLE
TypeError when using += without an extends should be more informative

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#182]
If you accidentally have this:

```yml
Resource2Img:
  y: += 125
```
...when you really mean this...
```yml
Resource2Img:
  extends: Resource1
  y: += 125
```
You get a type error - it would be nice if we had a better error message than this
