### ISSUE TITLE
Custom save_sheet/save_pdf templates

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#217]
This is Squib's most important feature that is missing, in my opinion.

`save_sheet` and `save_pdf` are pretty inflexible. We need to be able to customize the exact placement of cards on a "sheet" (could be a PNG, could be a PDF) and then create new pages on overflow. The data for these coordinates should be in a built-in library of templates so we can keep extending these templates for printing out to, say, Avery sticker sheets or to print-on-demand companies who take in custom sheets.

I started this idea on my own project and I would love to see it expanded more. Here's my code:

https://github.com/andymeneely/project-timber-wolf/blob/master/src/save_custom_sheet.rb
...and my data...
https://github.com/andymeneely/project-timber-wolf/blob/master/data/avery_5408.yml

What I needed there was to print to a bunch of circle stickers for prototyping. The template was Avery 5408 and I just measured what I needed and implemented it. Pretty hacky but it works for my needs on my project at the moment.

What's cool about this approach is that you're not setting margins and gaps, you're just setting coordinates of your cards. So it can take in multiple sizes. The template holds 24 cards, so if you save, say, 25 cards it just creates a new sheet.

To work in Squib, we'll need the following:
  - [x] Template defines the size of a sheet
  - [x] Template defines the expected size of a card. (Maybe? Or just have an expected size of a card and warn?) 
  - [x] Each card can be placed at the set coordinates
  - [x] Setting for whether the coordinates specify the middle of the card or the upper-left. Would be handy for handling arbitrary sizes
  - [x] Rotation angle so we can do fold things
  - [x] Crop line support based on the card
  - [x] Arbitrary lines so we can define, say, a folding line just like [this method](https://boardgamegeek.com/thread/490643/making-cards-youll-never-use-your-old-method-again)

**Comment by felixleong** [comment]
Took a first stab of the code by basing it off your code from project-timber-wolf.

https://github.com/felixleong/squib/tree/feature/pdf-template

Another piece of code that I have added there is a template definition file generator through the use of the `squib make_template` command.

The current template file structure looks roughly like this:

```yaml
---
sheet_width: 210mm
sheet_height: 297mm
card_width: 63mm
card_height: 88mm
cards:
- x: 5mm
  y: 5mm
# ... Array of (x,y)'s 
```

Would love to hear feedback and what other ideas that should be incorporated, especially in terms of the Ruby code (pretty much a hack job coming from a Python programmer :p)

**Comment by andymeneely** [comment]
Thank you!! I'm super happy to see someone's willing to pick this up. Ok here's some feedback:

I don't know that I need the make_template cli thing - is there an advantage of the question-and-answer menu over just making own YML template file? 

It would be cool if the TemplateInputFile arg would try to open yours, then if that doesn't exist, try to look it up in our built-in library inside the gem. 

On top of the above features in my todo list, I can't think of anything to add - although some of those above are tough ones (crop lines, e.g.) 

Have you tested this out on your own projects?

(BTW - I don't believe I've seen you before - welcome!! Are you on BGG? I'd like to give you a GeekGold tip...)

**Comment by felixleong** [comment]
Am felixleong on BGG, nice to meet you! :) I rarely participate in most forums in general.

Am dog-food'ing it at the moment for a game that I'm working on. So at least it is tested on a surface level? :)

Anyway, here's some long-winded replies :).

1. The `squib make_template` command: it's an easy way to generate base templates to work off from instead of having to write the YAML myself.

   At least with the rate of me experimenting w/ hexagon cards, I have to iterate a lot to fit as much as I could on a single page and it is a time-saver for me :).

   Though can see when it'll wear out of it's usefulness and should be relegated to its own script file, but I think piggy-backing it onto the `squib` won't be too bad of an idea.

2. Args::TemplateInputFile: Will look into implementing it as you did bring up a great use-case for it.

3. Think crop lines won't be too hard to add, but would need to define a specification for it. Am thinking along the lines of:

   ```yaml
   cards: ...
   crop_lines:
   - x: 5mm
     y: 0mm
     x1: 5mm
     y1: 297mm
     # Takes :solid, :doted, :dashed, may be implemented later, defaults to :solid
     line: dotted
     width: 0.1764mm  # defaults to 0.5pt
     color: :black  # Takes a colour, defaults to :black
     # Takes :margin or :page - the gist being either lines are drawn on the
     # margins
     # only or on the page overlaying even the card images
     style: :margin
   ```

   Most options above are optional and you can define smart defaults to make quick crop lines, examples:

   ```yaml
   - x: 5mm  # This would draw a vertical cut line down the page
   - y: 0.25in  # Draws a horizontal cut line across the page
   - ...
   ```

   Would take the stance of the user using this feature should manage and define their own crop lines as the cards could be laid out in an arbitrary fashion, like column 2 in the image below where I've shifted the cards half step:

   ![screenshot from 2017-04-11 09-38-32](https://cloud.githubusercontent.com/assets/246969/24889120/cb65c486-1e9a-11e7-8fea-2387d4294841.png)
