### ISSUE TITLE
Unit conversion breaks on extends

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#23]
If we have this situation in a layout file, we get an error:

```yml
Attack:
  x: 1in

Defend:
  extends: Attack
  x: += 2in
```

Really the second being inches is not needed - basically `extends` doesn't do unit conversion and probably should
