### ISSUE TITLE
Embedded icon alignment not as expected

### ISSUE THREAD

**Issue by adsilcott** [andymeneely/squib#348]
Squib's embedded icons feature is one of my favorite things about it! However, I've encountered an alignment issue in a specific circumstance. Either I'm doing something wrong or it's a bug.

Here is my code:
```
text str: data.buy, layout: :buy do |embed|
    embed.svg key: '[coin]', file: 'img/coin.svg', layout: :embedded
    embed.svg key: '[gem]',  file: 'img/gem.svg',  layout: :embedded
end
```

with the layout:
```
buy:
  extends: name
  x: 468
  y: 637
  width: 506
  height: 75
  align: right

embedded:
  height: 75
  width: 75
  align: center
  valign: middle
```

with the result:
![SquibExample001](https://user-images.githubusercontent.com/10678803/139129282-fdf3e5d4-d665-4548-9ecf-cfc06c5fbccb.PNG)

Looks great!

However, when I change the code to add some text to the string:
`text str: data.buy.map{ |s| if (s != nil) then s = "Cost: " + s end }, layout: :buy do |embed|`

here is the result:
![SquibExample002](https://user-images.githubusercontent.com/10678803/139129444-aed9775e-91f0-4c69-addf-bbf721e9aac3.PNG)

Now the text is perfectly aligned, but the icons have dropped down a bit. Is the the correct behavior?
