### ISSUE TITLE
Allow for x-y coordinates to be negative and subtract from width-height

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#8]
Cairo doesn't do that normally. Maybe make this a configurable setting in config.yml so it's easier to place.

**Comment by andymeneely** [comment]
After playing around with this, I'm not sure I like it. I would rather run the layout.yml through ERB so we can do stuff like:
```yaml
title:
  x: <%=@width-75%>
```

**Comment by scraimer** [comment]
Ooh, ERB for layouts would be awesome! It would move much of my positioning code out of the deck.rb and into the layout, where it belongs!

For example, If I want to draw a circle around some text. I could easily use ruby expressions to offset the circle so that its origin is positioned correctly to make the circle go around the text.

<pre>
SomeText:
   x: 50
   y: 50
   width: 150
   height: 150

SomeTextCircle:
    x: <%=@x - 20%>
    y: <%=@y - 20%>
<pre>

**Comment by andymeneely** [comment]
Actually, you don't need ERB for that situation - use extends:

```yaml
SomeText:
  x: 50
  y: 50
SomeTextCircle:
  extends: SomeText
  x: -= 20 # in yaml this is a string, but it gets processed as a part of processing "extends"
  y: -= 20
```
http://andymeneely.github.io/squib/doc/file.README.html#Special_key__extends

But... there are other situations where ERB would be helpful. The issue I created for that is #36.
