### ISSUE TITLE
`set_source_squibcolor': undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by spdustin** [andymeneely/squib#83]
After refactoring
```ruby
type = {}; data['Type'].each_with_index{ |t,i| (type[t] ||= []) << i}
text range: type['Creeper']  , layout: 'sidebar_text_creeper'  , str: data['Title']
text range: type['Action']   , layout: 'sidebar_text_action'   , str: data['Title']
text range: type['Keeper']   , layout: 'sidebar_text_keeper'   , str: data['Title']
text range: type['New Rule'] , layout: 'sidebar_text_newrule'  , str: data['Title']
text range: type['Goal']     , layout: 'sidebar_text_goal'     , str: data['Title']
text range: type['Surprise'] , layout: 'sidebar_text_surprise' , str: data['Title']
```
to this:
```ruby
type = {}; data['Type'].each_with_index{ |t,i| (type[t] ||= []) << i}
text layout: data['Type'].map { |t| "sidebar_text_#{t.downcase.sub(/\s/,'')}" }, str: data['Title']
```
with a layout file containing this:
```yaml
sidebar_text:
  x: 71.5
  y: 1178
  width: 1028
  angle: -1.57079633
  align: 'right'
  font: 'Helvetica Bold 54'
  markup: true
sidebar_text_creeper:
  extends: sidebar_text
  color: '#FFFFFF'
sidebar_text_action:
  extends: sidebar_text
  color: '#000000'
sidebar_text_keeper:
  extends: sidebar_text
  color: '#000000'
sidebar_text_newrule:
  extends: sidebar_text
  fill_color: '#000000'
sidebar_text_surprise:
  extends: sidebar_text
  color: '#FFFFFF'
sidebar_text_goal:
  extends: sidebar_text
  color: '#000000'
```
I receive an error:
```
[snippedpath]/graphics/cairo_context_wrapper.rb:32:in `set_source_squibcolor': undefined method `match' for nil:NilClass (NoMethodError)
	from [snippedpath]/graphics/text.rb:166:in `block in text'
	from [snippedpath]/card.rb:51:in `yield'
	from [snippedpath]/card.rb:51:in `use_cairo'
	from [snippedpath]/graphics/text.rb:165:in `text'
	from [snippedpath]/api/text.rb:54:in `block in text'
	from [snippedpath]/api/text.rb:53:in `each'
	from [snippedpath]/api/text.rb:53:in `text'
	from ~/repos/hpfluxx/deck.rb:22:in `block in <main>'
	from [snippedpath]/deck.rb:71:in `instance_eval'
	from [snippedpath]/deck.rb:71:in `initialize'
	from ~/repos/hpfluxx/deck.rb:5:in `new'
	from ~/repos/hpfluxx/deck.rb:5:in `<main>'
```
If you can help me figure out what I did wrong, I'd greatly appreciate it - or did I stumble on a bug?

**Comment by andymeneely** [comment]
It's definitely a bug in the sense that the error is not caught nor clear. I believe you've got a nil color being set. Here's a minimal example: 

```ruby
Squib::Deck.new do
  text str: 'hello', color: nil
end
```

I'll add a check for this so it's clearer. 

Oh, and it looks like you put `fill_color` instead of `color` for `newrule`
```yaml
sidebar_text_newrule:
  extends: sidebar_text
  fill_color: '#000000' # <-- should be color: 
```

In retrospect, `color` should should really just be an alias for `fill_color` on text anyway - it's confusing to not handle both. I'll look into that on #85.
