### ISSUE TITLE
Create a bunch of new built-in layouts

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#97]
Go over some of the popular games out there and create built-in layouts for them. Here are some that I can think of that we can base a layout on:

  * MtG, and other RPGs
  * Race for the Galaxy
  * Seven Wonders
  * Square cards like in Power Grid
  * Fluxx

Go over the templates from Paperize.io as well and use theirs as inspiration. 

Create a sample with a sheet that we can post on the website showing the various options. Write up more about this in the README.

Also, we should avoid naming the layouts according to the game so as not to have trademark issues. We also shouldn't dogmatically follow game layouts - they often have small adjustments that make sense for their situation.

**Comment by yipcma** [comment]
Hi Andy,

Love Squib, wonder if there's any Fluxx layouts around that I could give a try?

Cheers,

andrew

**Comment by andymeneely** [comment]
Oh not yet. That's a good idea though. I'll put one together, or if you end up putting one together I'd be happy make it a built-in.

**Comment by andymeneely** [comment]
Here you go! This will be in the next release as "party"

Note: for the font sizes, we're about change how we compute them. These are Squib v0.14 font sizes. For Squib v.13 and before, take these font sizes and multiply them by 3. Otherwise everything should still work.

Here's what the sample will look like:
```ruby
Squib::Deck.new(layout: 'party.yml') do
  background color: 'white'
  # hint text: :black # uncomment to see the text box boundaries

  rect layout: :title_box,
       fill_color: :deep_sky_blue, stroke_width: 0
  text str: "A SILLY NAME",  layout: :title
  text str: '✔',             layout: :type_icon
  text str: 'TYPE',          layout: :type
  text str: 'A Silly Name',  layout: :title_middle
  rect fill_color: :black,   layout: :middle_rect

  str = 'Rule or story text. Be funny ha ha ha this is a party.'
  text str: str, layout: :rule_top
  text str: str, layout: :rule_bottom

  text str: 'Tiny text', layout: :copyright

  rect layout: :safe
  rect layout: :cut
  save_png prefix: 'layouts_builtin_party_'
end
```

And then `party.yml`:

```yaml
#This layout inspired by popular games like Fluxx and Apples to Apples
title_box:
  x: 75
  y: 75
  width: 125
  height: 975

title:
  x: 75
  y: 1050
  angle: 4.71238898 # 3 π / 2
  width: 850
  height: 125
  align: right
  valign: middle
  font: Sans 22

title_middle:
  x: 225
  y: 550
  font: Sans 18
  width: 525
  height: 150
  valign: bottom

middle_rect:
  x: 225
  y: 715
  width: 525
  height: 25

rule_top:
  x: 225
  y: 200
  width: 525
  height: 300
  font: Times New Roman, Serif 10

rule_bottom:
  x: 225
  y: 750
  width: 525
  height: 300
  font: Times New Roman, Serif 10

type_icon:
  x: 75
  y: 75
  width: 125
  height: 125
  align: center
  valign: middle
  font: 'Sans 24'

type:
  x: 225
  y: 75
  width: 525
  height: 125
  align: left
  valign: top
  font: 'Sans 30'

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 5
  align: right
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  radius: 16
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  dash: 3 3
```
